import React,{useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {setEmployeeOffices} from './lib/shared'

export default function EmployeeAccess({employees,onUpdate,onInvite,onDeactivate,currentUserId}){
 const[form,setForm]=useState(null),[offices,setOffices]=useState([]),[assigned,setAssigned]=useState([])
 useEffect(()=>{supabase.from('offices').select('id,name').eq('active',true).order('name').then(({data})=>setOffices(data||[]))},[])
 useEffect(()=>{if(!form?.id)return setAssigned([]);supabase.from('office_memberships').select('office_id').eq('user_id',form.id).then(({data})=>setAssigned((data||[]).map(x=>x.office_id)))},[form?.id])
 const submit=async e=>{e.preventDefault();const data=new FormData(e.currentTarget),values=Object.fromEntries(data);if(form.invite)await onInvite(values.email,values.full_name);else{await onUpdate(form.id,{full_name:values.full_name,email:values.email,position:values.position,role:values.role});await setEmployeeOffices(form.id,data.getAll('office_ids'))}setForm(null)}
 return <><div className="head"><div><small>ADMINISTRATION</small><h1>Employees & access</h1><p>Customize names, emails, positions, roles, and allowed offices.</p></div><button className="primary" onClick={()=>setForm({invite:true})}>Invite employee</button></div><div className="cards employees">{employees.map(e=><article key={e.id}><i>{e.initials}</i><h3>{e.name}</h3><p>{e.role}</p><small>{e.email||'No email saved'}</small><em>{e.accessRole}</em><button onClick={()=>setForm(e)}>Edit access & offices</button></article>)}</div>{form&&<div className="backdrop"><section className="drawer"><header><h2>{form.invite?'Invite employee':'Edit employee access'}</h2></header><form onSubmit={submit}><label>Full name<input name="full_name" defaultValue={form.name||''} required/></label><label>Work email<input name="email" type="email" defaultValue={form.email||''} required/></label>{form.invite?null:<><label>Position<input name="position" defaultValue={form.role}/></label><label>Dashboard role<select name="role" defaultValue={form.accessRole}><option value="employee">Employee</option><option value="team_lead">Team Lead</option><option value="admin">Admin</option></select></label><fieldset className="office-access"><legend>Offices this employee can work on</legend>{offices.map(o=><label key={o.id}><input type="checkbox" name="office_ids" value={o.id} checked={assigned.includes(o.id)} onChange={e=>setAssigned(e.target.checked?[...assigned,o.id]:assigned.filter(id=>id!==o.id))}/>{o.name}</label>)}</fieldset><button type="button" className="danger-button" disabled={form.id===currentUserId} onClick={async()=>{if(form.id===currentUserId)return;if(confirm('Deactivate '+form.name+'? They will be removed from active employees and office access, but task history will stay saved.')){await onDeactivate(form.id,form.name);setForm(null)}}}>Deactivate employee</button>{form.id===currentUserId&&<small className="danger-note">You cannot deactivate your own admin account while signed in.</small>}</>}<footer><button type="button" onClick={()=>setForm(null)}>Cancel</button><button className="primary">{form.invite?'Send secure access':'Save access'}</button></footer></form></section></div>}</>
}
